<a href="https://colab.research.google.com/github/DevThazin/ML_maths/blob/main/Matrix_Operations_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
m1=np.array([[1,2,3],[4,5,6]])
m2=np.array([[1,5,9],[8,5,1]])

In [7]:
#addition
sum=m1+m2

In [8]:
sum

array([[ 2,  7, 12],
       [12, 10,  7]])

Addition another way

In [9]:
sum1=np.add(m1,m2)

In [10]:
print(sum1)

[[ 2  7 12]
 [12 10  7]]


Creating matrixes with random number


In [12]:
m3=np.random.randint(10, size=(3,3))
m4=np.random.randint(20, size=(3,3))

In [13]:
print(m3)

[[1 7 8]
 [2 0 6]
 [3 4 9]]


In [14]:
print(m4)

[[ 6 14  0]
 [10 13  8]
 [14  3 14]]


In [16]:
sum=np.add(m3,m4)

Subtraction

In [17]:
sub=m3-m4

In [22]:
print(sub)

[[ -5  -7   8]
 [ -8 -13  -2]
 [-11   1  -5]]


In [23]:
sub=np.subtract(m3,m4)
print(sub)

[[ -5  -7   8]
 [ -8 -13  -2]
 [-11   1  -5]]


Multiplication of matrix by a scaler

In [27]:

x = 5
y = np.random.randint(10, size=(4,4))

print(y)
product = np.multiply(x,y)
print(product)


[[1 2 9 6]
 [9 2 3 1]
 [3 8 2 9]
 [0 5 3 8]]
[[ 5 10 45 30]
 [45 10 15  5]
 [15 40 10 45]
 [ 0 25 15 40]]


Multiplication of two matrices

In [25]:
a = np.random.randint(10, size=(4,4))
b = np.random.randint(20, size=(4,5))
print(a)
print(b)


[[4 8 3 2]
 [7 5 7 8]
 [4 2 0 5]
 [0 0 0 8]]
[[11  1  5  8 11]
 [13  0 14 13 15]
 [ 3  8 15  6  4]
 [18 15 10  7 11]]


In [28]:
mul=np.dot(a,b)

In [29]:
mul

array([[193,  58, 197, 168, 198],
       [307, 183, 290, 219, 268],
       [160,  79,  98,  93, 129],
       [144, 120,  80,  56,  88]])

Element wise multiplication

In [33]:
a = np.random.randint(10, size=(4,4))
b = np.random.randint(5, size=(4,4))
print(a)
print(b)


[[0 8 6 2]
 [7 8 8 3]
 [4 2 4 5]
 [5 8 1 3]]
[[4 1 4 1]
 [1 0 3 4]
 [0 0 0 2]
 [2 1 0 2]]


In [34]:
np.multiply(a,b)

array([[ 0,  8, 24,  2],
       [ 7,  0, 24, 12],
       [ 0,  0,  0, 10],
       [10,  8,  0,  6]])