<a href="https://colab.research.google.com/github/DevThazin/ML_maths/blob/main/Matrix_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
matrix=np.array([[1,2],[4,5]])

In [3]:
matrix

array([[1, 2],
       [4, 5]])

In [5]:
matrix_1=np.array([[1,2,3],[4,5,6],[3,5,6]])
print(matrix_1)
matrix_1.shape

[[1 2 3]
 [4 5 6]
 [3 5 6]]


(3, 3)

In [7]:
matrix_2=np.array([[[1,2,3],[4,5,6]],[[3,5,6],[3,5,6]]])

In [8]:
print(matrix_2)
matrix_2.shape

[[[1 2 3]
  [4 5 6]]

 [[3 5 6]
  [3 5 6]]]


(2, 2, 3)

In [10]:
#random matrix
rand_mat=np.random.rand(2,3)
print(rand_mat)

[[0.19966251 0.02823062 0.38084655]
 [0.84745704 0.35462565 0.89362493]]


In [13]:
#random matrix integer
rand_mat=np.random.randint(100, size=(2,3))
print(rand_mat)

[[ 2 29 75]
 [44 52  2]]


In [14]:

matrix_3 = np.ones((2,3))
print(matrix_3)


[[1. 1. 1.]
 [1. 1. 1.]]


In [15]:

matrix_3 = np.ones((2,3), dtype=int)
print(matrix_3)


[[1 1 1]
 [1 1 1]]


In [17]:

matrix_4 = np.zeros((2,3),dtype=int)
print(matrix_4)


[[0 0 0]
 [0 0 0]]


In [20]:
matrix_5=np.eye(3,3)

In [21]:
matrix_5

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
matrix_5=np.eye(3,3, dtype=int)

In [23]:
matrix_5

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [24]:

# matrix with random integer values
a = np.random.randint(100, size=(4,5))
print(a)

[[92 58 39  9 95]
 [14 38 83 28 66]
 [61 66  4 79 62]
 [60  9 47 42 40]]


In [25]:

transpose_of_a = np.transpose(a)
print(transpose_of_a)

[[92 14 61 60]
 [58 38 66  9]
 [39 83  4 47]
 [ 9 28 79 42]
 [95 66 62 40]]
